version: "3.8"
services:
  web: 
    build: ./client
    ports:
      - 3000:3000
  api:
    build: ./server
    ports: 
      - 4000:4000
    environment:
      - MONGO_URI=mongodb://db/ecomm
  db:
    image: mongo:4.0-xenial
    ports: 
      - 27017:27017